### ISSUE TITLE
Lack of Abstraction

### ISSUE THREAD

**Issue by TunnelBlanket** [Romtoc/Pebble#1]
[CPMain](https://github.com/Romtoc/Pebble/blob/master/Core/CPMain.php) class should extend the [Socket](https://github.com/Romtoc/Pebble/blob/master/Skeleton/Socket.php) class and implement an interface containing the following methods 

```php
public function __construct($serverConfig, $databaseConfig);
public function parseConfig($serverConfig, $databaseConfig);
public function initiateCP();
public function displayHeader();
public function handleXMLData($strData, $objClient);
public function handleXTData($strData, $objClient);
```

Since it's what  [CPMain](https://github.com/Romtoc/Pebble/blob/master/Skeleton/Socket.php#L31) expects, the client class should also implement an interface that forces it to have a constructor.

Also, you're forgetting a couple of parenthesis around [initiateCP](https://github.com/Romtoc/Pebble/blob/master/Core/CPMain.php#L148).

**Comment by Romtoc** [comment]
Don't know why you'd make an issue out of it, but it was made to be simple and not complicate shit. However I've fixed the syntax error.
